module.exports = [

  // CLASS-10 PHYSICS QUESTIONS
  {
    id: 11,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Light - Reflection and Refraction",
    topic: "Reflection of Light",
    marks: "2",
    difficulty: "Easy",
    question: "State the laws of reflection.",
    isPYQ: true,
    year: 2021
  },
  {
    id: 12,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Light - Reflection and Refraction",
    topic: "Mirror Formula",
    marks: "4",
    difficulty: "Medium",
    question: "Derive the mirror formula and explain the terms.",
    isPYQ: true,
    year: 2022
  },
  {
    id: 13,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Light - Reflection and Refraction",
    topic: "Refraction of Light",
    marks: "3",
    difficulty: "Easy",
    question: "Explain refraction with a neat diagram.",
    isPYQ: true,
    year: 2023
  },
  {
    id: 14,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Human Eye and Colourful World",
    topic: "Human Eye",
    marks: "4",
    difficulty: "Medium",
    question: "Describe the structure and working of the human eye.",
    isPYQ: true,
    year: 2024
  },
  {
    id: 15,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Human Eye and Colourful World",
    topic: "Defects of Vision",
    marks: "5",
    difficulty: "Hard",
    question: "Explain myopia and hypermetropia and their correction.",
    isPYQ: true,
    year: 2021
  },
  {
    id: 16,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Electricity",
    topic: "Ohm's Law",
    marks: "2",
    difficulty: "Easy",
    question: "State Ohm's Law. Write its formula.",
    isPYQ: true,
    year: 2022
  },
  {
    id: 17,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Electricity",
    topic: "Resistance",
    marks: "3",
    difficulty: "Medium",
    question: "Explain factors affecting resistance of a conductor.",
    isPYQ: true,
    year: 2023
  },
  {
    id: 18,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Electricity",
    topic: "Electric Power",
    marks: "4",
    difficulty: "Medium",
    question: "Derive the formula for electric power and energy.",
    isPYQ: true,
    year: 2024
  },
  {
    id: 19,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Magnetic Effects of Electric Current",
    topic: "Magnetic Field",
    marks: "3",
    difficulty: "Easy",
    question: "What is a magnetic field? How can its direction be determined?",
    isPYQ: true,
    year: 2021
  },
  {
    id: 20,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Magnetic Effects of Electric Current",
    topic: "Electromagnet",
    marks: "5",
    difficulty: "Hard",
    question: "Describe the construction and working of an electromagnet.",
    isPYQ: true,
    year: 2022
  },
  {
    id: 21,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Magnetic Effects of Electric Current",
    topic: "Fleming's Left-Hand Rule",
    marks: "3",
    difficulty: "Medium",
    question: "State Fleming's left-hand rule and its applications.",
    isPYQ: true,
    year: 2023
  },
  {
    id: 22,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Sources of Energy",
    topic: "Renewable Energy",
    marks: "4",
    difficulty: "Medium",
    question: "Explain renewable sources of energy with examples.",
    isPYQ: true,
    year: 2024
  },
  {
    id: 23,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Sources of Energy",
    topic: "Thermal Power Plant",
    marks: "3",
    difficulty: "Easy",
    question: "What is a thermal power plant? Explain its working.",
    isPYQ: true,
    year: 2021
  },
  {
    id: 24,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Sources of Energy",
    topic: "Advantages and Disadvantages",
    marks: "4",
    difficulty: "Medium",
    question: "Discuss advantages and disadvantages of non-renewable sources.",
    isPYQ: true,
    year: 2022
  },
  {
    id: 25,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Light - Reflection and Refraction",
    topic: "Lens Formula",
    marks: "5",
    difficulty: "Hard",
    question: "Derive lens formula and explain image formation in convex lens.",
    isPYQ: true,
    year: 2023
  },
  {
    id: 26,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Human Eye and Colourful World",
    topic: "Dispersion of Light",
    marks: "3",
    difficulty: "Easy",
    question: "Explain dispersion of light through a prism.",
    isPYQ: true,
    year: 2024
  },
  {
    id: 27,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Magnetic Effects of Electric Current",
    topic: "Electric Motor",
    marks: "5",
    difficulty: "Hard",
    question: "Explain the working principle and construction of an electric motor.",
    isPYQ: true,
    year: 2025
  },
  {
    id: 28,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Electricity",
    topic: "Combination of Resistors",
    marks: "4",
    difficulty: "Hard",
    question: "Explain series and parallel combinations of resistors with examples.",
    isPYQ: true,
    year: 2021
  },
  {
    id: 29,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Sources of Energy",
    topic: "Solar Energy",
    marks: "3",
    difficulty: "Easy",
    question: "What is solar energy? Write its uses.",
    isPYQ: true,
    year: 2022
  },
  {
    id: 30,
    examLevel: "class10",
    subject:"Physics",
    chapter: "Light - Reflection and Refraction",
    topic: "Image Formation by Mirrors",
    marks: "2",
    difficulty: "Easy",
    question: "Draw ray diagrams showing image formation by concave mirror.",
    isPYQ: true,
    year: 2023
  },
  //CLASS-10 BIOLOGY QUESTIONS
  {
    id: 31,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Life Processes",
    topic: "Nutrition in Plants",
    marks: 2,
    difficulty: "Easy",
    question: "What is photosynthesis? Write its balanced chemical equation.",
    isPYQ: true,
    year: 2021
  },
  {
    id: 32,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Life Processes",
    topic: "Respiration",
    marks: 3,
    difficulty: "Easy",
    question: "Differentiate between aerobic and anaerobic respiration.",
    isPYQ: true,
    year: 2022
  },
  {
    id: 33,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Life Processes",
    topic: "Transportation in Humans",
    marks: 5,
    difficulty: "Medium",
    question: "Explain the structure and function of the human heart with a diagram.",
    isPYQ: true,
    year: 2023
  },
  {
    id: 34,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Life Processes",
    topic: "Excretion in Humans",
    marks: 4,
    difficulty: "Medium",
    question: "Describe the process of urine formation in the human body.",
    isPYQ: true,
    year: 2024
  },
  {
    id: 35,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Control and Coordination",
    topic: "Nervous System",
    marks: 3,
    difficulty: "Easy",
    question: "What is a reflex action? Explain with an example.",
    isPYQ: true,
    year: 2021
  },
  {
    id: 36,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Control and Coordination",
    topic: "Hormones in Animals",
    marks: 5,
    difficulty: "Hard",
    question: "Explain the role of endocrine glands in humans.",
    isPYQ: true,
    year: 2022
  },
  {
    id: 37,
    examLevel: "class10",
    subject: "Biology",
    chapter: "How Do Organisms Reproduce?",
    topic: "Modes of Reproduction",
    marks: 4,
    difficulty: "Medium",
    question: "Describe binary fission and multiple fission in detail.",
    isPYQ: true,
    year: 2023
  },
  {
    id: 38,
    examLevel: "class10",
    subject: "Biology",
    chapter: "How Do Organisms Reproduce?",
    topic: "Reproduction in Flowering Plants",
    marks: 2,
    difficulty: "Easy",
    question: "What is pollination? Mention its types.",
    isPYQ: true,
    year: 2024
  },
  {
    id: 39,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Heredity and Evolution",
    topic: "Mendel's Laws",
    marks: 5,
    difficulty: "Hard",
    question: "Explain Mendel's law of independent assortment with a suitable example.",
    isPYQ: true,
    year: 2025
  },
  {
    id: 40,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Heredity and Evolution",
    topic: "Sex Determination",
    marks: 3,
    difficulty: "Medium",
    question: "How is sex determined in human beings?",
    isPYQ: true,
    year: 2022
  },
  {
    id: 41,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Our Environment",
    topic: "Ecosystem",
    marks: 2,
    difficulty: "Easy",
    question: "Define ecosystem. What are its components?",
    isPYQ: true,
    year: 2021
  },
  {
    id: 42,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Our Environment",
    topic: "Ozone Layer Depletion",
    marks: 4,
    difficulty: "Medium",
    question: "Explain ozone layer depletion and its effects.",
    isPYQ: true,
    year: 2023
  },
  {
    id: 43,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Management of Natural Resources",
    topic: "Water Conservation",
    marks: 3,
    difficulty: "Easy",
    question: "List methods for conservation of water resources.",
    isPYQ: true,
    year: 2024
  },
  {
    id: 44,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Management of Natural Resources",
    topic: "Sustainable Management",
    marks: 5,
    difficulty: "Hard",
    question: "Discuss the sustainable management of forests with examples.",
    isPYQ: true,
    year: 2025
  },
  {
    id: 45,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Heredity and Evolution",
    topic: "Evolutionary Relationships",
    marks: 4,
    difficulty: "Medium",
    question: "Explain homologous and analogous organs with examples.",
    isPYQ: true,
    year: 2022
  },
  {
    id: 46,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Life Processes",
    topic: "Nutrition in Animals",
    marks: 3,
    difficulty: "Easy",
    question: "Describe the process of digestion in humans.",
    isPYQ: true,
    year: 2021
  },
  {
    id: 47,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Control and Coordination",
    topic: "Plant Hormones",
    marks: 2,
    difficulty: "Easy",
    question: "What are plant hormones? Name any two.",
    isPYQ: true,
    year: 2023
  },
  {
    id: 48,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Management of Natural Resources",
    topic: "Reduce, Reuse, Recycle",
    marks: 3,
    difficulty: "Medium",
    question: "Explain the concept of 3Rs with examples.",
    isPYQ: true,
    year: 2024
  },
  {
    id: 49,
    examLevel: "class10",
    subject: "Biology",
    chapter: "Our Environment",
    topic: "Food Chains and Webs",
    marks: 2,
    difficulty: "Easy",
    question: "Define food chain. Give one example.",
    isPYQ: true,
    year: 2021
  },
  {
    id: 50,
    examLevel: "class10",
    subject: "Biology",
    chapter: "How Do Organisms Reproduce?",
    topic: "Reproduction in Humans",
    marks: 5,
    difficulty: "Hard",
    question: "Describe the human female reproductive system with a labelled diagram.",
    isPYQ: true,
    year: 2025
  },
  //CLASS 12 - BOARDS MATHS
  {
  id: 51,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Calculus",
  topic: "Application of Derivatives",
  marks: 5,
  difficulty: "Hard",
  question: "Find the maximum and minimum value of a function using first derivative test.",
  isPYQ: true,
  year: 2023
},
{
  id: 52,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Algebra",
  topic: "Complex Numbers",
  marks: 4,
  difficulty: "Medium",
  question: "Find modulus and argument of 3 + 4i and represent it graphically.",
  isPYQ: false,
},
{
  id: 53,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Algebra",
  topic: "Binomial Theorem",
  marks: 3,
  difficulty: "Easy",
  question: "Find the term independent of x in the expansion of (x² + 1/x)^10.",
  isPYQ: true,
  year: 2021
},
{
  id: 54,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Coordinate Geometry",
  topic: "Circle",
  marks: 4,
  difficulty: "Medium",
  question: "Find the equation of a circle passing through three non-collinear points.",
  isPYQ: true,
  year: 2024
},
{
  id: 55,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Vectors",
  topic: "Dot Product",
  marks: 3,
  difficulty: "Easy",
  question: "Find the angle between two vectors using dot product.",
  isPYQ: false,
},
{
  id: 56,
  examLevel: "class12",
  subject: "Maths",
  chapter: "3D Geometry",
  topic: "Planes",
  marks: 5,
  difficulty: "Hard",
  question: "Find the equation of a plane perpendicular to a given vector and passing through a point.",
  isPYQ: true,
  year: 2022
},
{
  id: 57,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Matrices",
  topic: "Inverse of a Matrix",
  marks: 3,
  difficulty: "Medium",
  question: "Find the inverse of a 2x2 matrix using elementary transformations.",
  isPYQ: false,
},
{
  id: 58,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Determinants",
  topic: "Properties of Determinants",
  marks: 4,
  difficulty: "Hard",
  question: "Use properties of determinants to evaluate a 3x3 determinant.",
  isPYQ: true,
  year: 2024
},
{
  id: 59,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Probability",
  topic: "Bayes' Theorem",
  marks: 5,
  difficulty: "Hard",
  question: "State and prove Bayes' theorem with an example related to medicine testing.",
  isPYQ: true,
  year: 2023
},
{
  id: 60,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Trigonometry",
  topic: "Trigonometric Equations",
  marks: 3,
  difficulty: "Medium",
  question: "Solve the equation sin x + sin 3x = 0 in [0, 2π].",
  isPYQ: false,
},
{
  id: 61,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Sequences and Series",
  topic: "Arithmetic Progression",
  marks: 3,
  difficulty: "Easy",
  question: "Find the sum of first 20 terms of the AP: 5, 8, 11, ...",
  isPYQ: false,
},
{
  id: 62,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Algebra",
  topic: "Permutations and Combinations",
  marks: 4,
  difficulty: "Medium",
  question: "Find the number of ways to arrange the word 'ENGINEERING'.",
  isPYQ: true,
  year: 2023
},
{
  id: 63,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Calculus",
  topic: "Definite Integrals",
  marks: 4,
  difficulty: "Hard",
  question: "Evaluate ∫₀^π sin²x dx using trigonometric identity.",
  isPYQ: true,
  year: 2024
},
{
  id: 64,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Matrices",
  topic: "Properties",
  marks: 3,
  difficulty: "Medium",
  question: "Prove that (AB)' = B'A' for any two matrices A and B.",
  isPYQ: false,
},
{
  id: 65,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Differential Equations",
  topic: "General Solution",
  marks: 5,
  difficulty: "Hard",
  question: "Solve the differential equation dy/dx = (x + y)².",
  isPYQ: true,
  year: 2023
},
{
  id: 66,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Coordinate Geometry",
  topic: "Parabola",
  marks: 4,
  difficulty: "Medium",
  question: "Find the focus, directrix, and axis of parabola y² = 8x.",
  isPYQ: false,
},
{
  id: 67,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Probability",
  topic: "Classical Probability",
  marks: 2,
  difficulty: "Easy",
  question: "A die is rolled. What is the probability of getting a multiple of 3?",
  isPYQ: false,
},
{
  id: 68,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Set Theory",
  topic: "Union and Intersection",
  marks: 2,
  difficulty: "Easy",
  question: "If A = {1,2,3}, B = {3,4,5}, find A U B and A ∩ B.",
  isPYQ: true,
  year: 2022
},
{
  id: 69,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Functions",
  topic: "Domain and Range",
  marks: 3,
  difficulty: "Medium",
  question: "Find the domain and range of f(x) = √(x - 1).",
  isPYQ: true,
  year: 2024
},
{
  id: 70,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Linear Programming",
  topic: "Feasible Region",
  marks: 3,
  difficulty: "Medium",
  question: "Explain feasible region and optimal solution in LPP using graph.",
  isPYQ: false,
},
{
  id: 71,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Algebra",
  topic: "Linear Equations",
  marks: 2,
  difficulty: "Easy",
  question: "Solve the system of equations using substitution method.",
  isPYQ: false,
  
},
{
  id: 72,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Statistics",
  topic: "Mean and Median",
  marks: 3,
  difficulty: "Medium",
  question: "Find mean and median of given data set: 5, 7, 9, 10, 12.",
  isPYQ: true,
  year: 2022
},
{
  id: 73,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Trigonometry",
  topic: "Basic Identities",
  marks: 2,
  difficulty: "Easy",
  question: "Prove that tan²θ + 1 = sec²θ.",
  isPYQ: true,
  year: 2021
},
{
  id: 74,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Calculus",
  topic: "Differentiation",
  marks: 4,
  difficulty: "Medium",
  question: "Find the derivative of f(x) = sin x · ln x.",
  isPYQ: false,

},
{
  id: 75,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Permutation & Combination",
  topic: "Basic Formulae",
  marks: 3,
  difficulty: "Medium",
  question: "How many 3-digit numbers can be formed using 1, 2, 3, 4 without repetition?",
  isPYQ: true,
  year: 2023
},
{
  id: 76,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Algebra",
  topic: "Determinants",
  marks: 2,
  difficulty: "Easy",
  question: "Evaluate the determinant of a 2x2 matrix.",
  isPYQ: false,
},
{
  id: 77,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Relations",
  topic: "Equivalence Relation",
  marks: 3,
  difficulty: "Medium",
  question: "Check whether the relation R on A = {1,2,3} is reflexive, symmetric, and transitive.",
  isPYQ: true,
  year: 2021
},
{
  id: 78,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Geometry",
  topic: "Lines and Angles",
  marks: 2,
  difficulty: "Easy",
  question: "Define complementary and supplementary angles with example.",
  isPYQ: false,
},
{
  id: 79,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Vectors",
  topic: "Basic Vector Operations",
  marks: 3,
  difficulty: "Medium",
  question: "If a = i + j and b = i - j, find a + b and a · b.",
  isPYQ: true,
  year: 2023
},
{
  id: 80,
  examLevel: "class12",
  subject: "Maths",
  chapter: "3D Geometry",
  topic: "Direction Cosines",
  marks: 3,
  difficulty: "Medium",
  question: "Define direction cosines of a line and find them for line joining (0,0,0) to (2,2,1).",
  isPYQ: false,
},
{
  id: 81,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Mathematical Logic",
  topic: "Statements",
  marks: 2,
  difficulty: "Easy",
  question: "Identify the statement as true or false: 'Every even number is divisible by 3.'",
  isPYQ: false,
},
{
  id: 82,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Sequence & Series",
  topic: "Geometric Progression",
  marks: 3,
  difficulty: "Medium",
  question: "Find the 5th term and sum of first 5 terms of GP: 2, 4, 8, ...",
  isPYQ: true,
  year: 2023
},
{
  id: 83,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Differential Equations",
  topic: "Variable Separable Method",
  marks: 4,
  difficulty: "Medium",
  question: "Solve dy/dx = 3x²y using variable separable method.",
  isPYQ: true,
  year: 2024
},
{
  id: 84,
  examLevel: "class12",
  subject: "Maths",
  chapter: "Sets",
  topic: "Power Set",
  marks: 2,
  difficulty: "Easy",
  question: "Find the power set of A = {1, 2}.",
  isPYQ: false,
},
// CLASS 12 CHEMISTRY
{
  id: 85,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Thermodynamics",
  topic: "First Law",
  marks: 4,
  difficulty: "Medium",
  question: "State and explain the First Law of Thermodynamics. Derive the relation for internal energy.",
  isPYQ: true,
  year: 2022
},
{
  id: 86,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Chemical Kinetics",
  topic: "Rate Law",
  marks: 5,
  difficulty: "Hard",
  question: "Derive the integrated rate law for a first-order reaction with a suitable example.",
  isPYQ: true,
  year: 2023
},
{
  id: 87,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Electrochemistry",
  topic: "Nernst Equation",
  marks: 4,
  difficulty: "Hard",
  question: "Derive the Nernst equation and explain its significance in calculating cell potential.",
  isPYQ: true,
  year: 2024
},
{
  id: 88,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Equilibrium",
  topic: "Le Chatelier's Principle",
  marks: 3,
  difficulty: "Medium",
  question: "State Le Chatelier's Principle and explain its application to a change in pressure and temperature.",
  isPYQ: false,
},
{
  id: 89,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Atomic Structure",
  topic: "Bohr's Model",
  marks: 5,
  difficulty: "Hard",
  question: "Explain Bohr's model of hydrogen atom and derive the expression for energy levels.",
  isPYQ: true,
  year: 2023
},
{
  id: 90,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Surface Chemistry",
  topic: "Adsorption",
  marks: 3,
  difficulty: "Medium",
  question: "Differentiate between physical and chemical adsorption with examples.",
  isPYQ: false,
},
{
  id: 91,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Solid State",
  topic: "Unit Cell",
  marks: 3,
  difficulty: "Medium",
  question: "Define a unit cell. Explain the types of unit cells in cubic crystal systems.",
  isPYQ: true,
  year: 2024
},
{
  id: 92,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Coordination Compounds",
  topic: "Nomenclature",
  marks: 2,
  difficulty: "Easy",
  question: "Write IUPAC names of the following: [Fe(CN)6]4−, [Co(NH3)5Cl]Cl2.",
  isPYQ: true,
  year: 2021
},
{
  id: 93,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Organic Chemistry",
  topic: "SN1 and SN2 Mechanisms",
  marks: 5,
  difficulty: "Hard",
  question: "Explain SN1 and SN2 mechanisms with energy profile diagrams and examples.",
  isPYQ: true,
  year: 2022
},
{
  id: 94,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Hydrocarbons",
  topic: "Aromatic Compounds",
  marks: 3,
  difficulty: "Medium",
  question: "Explain the directive influence of substituents in benzene ring reactions.",
  isPYQ: false,
},
{
  id: 95,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Environmental Chemistry",
  topic: "Greenhouse Effect",
  marks: 2,
  difficulty: "Easy",
  question: "What is the greenhouse effect? Name any two greenhouse gases.",
  isPYQ: false,
},
{
  id: 96,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Solutions",
  topic: "Raoult's Law",
  marks: 4,
  difficulty: "Medium",
  question: "State Raoult's law. Derive the expression for total vapor pressure of a binary solution.",
  isPYQ: true,
  year: 2021
},
{
  id: 97,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Haloalkanes and Haloarenes",
  topic: "Reactions",
  marks: 3,
  difficulty: "Medium",
  question: "Explain nucleophilic substitution reactions in haloalkanes.",
  isPYQ: true,
  year: 2022
},
{
  id: 98,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Aldehydes and Ketones",
  topic: "Aldol Condensation",
  marks: 3,
  difficulty: "Medium",
  question: "What is aldol condensation? Give mechanism with an example.",
  isPYQ: false,
},
{
  id: 99,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Polymers",
  topic: "Types",
  marks: 2,
  difficulty: "Easy",
  question: "Differentiate between addition and condensation polymers with one example each.",
  isPYQ: true,
  year: 2024
},
{
  id: 100,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Biomolecules",
  topic: "Carbohydrates",
  marks: 3,
  difficulty: "Medium",
  question: "Classify carbohydrates and explain reducing and non-reducing sugars.",
  isPYQ: true,
  year: 2022
},
{
  id: 101,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "The p-Block Elements",
  topic: "Group 15",
  marks: 4,
  difficulty: "Medium",
  question: "Discuss the anomalous behavior of nitrogen with respect to other Group 15 elements.",
  isPYQ: true,
  year: 2023
},
{
  id: 102,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "General Principles of Extraction",
  topic: "Froth Flotation",
  marks: 3,
  difficulty: "Easy",
  question: "Explain the froth flotation process with suitable diagram.",
  isPYQ: false,
},
{
  id: 103,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Redox Reactions",
  topic: "Oxidation Numbers",
  marks: 2,
  difficulty: "Easy",
  question: "Assign oxidation numbers to each element in KMnO4 and H2SO4.",
  isPYQ: true,
  year: 2022
},
{
  id: 104,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "The d-Block Elements",
  topic: "Properties",
  marks: 4,
  difficulty: "Medium",
  question: "Give reasons for variable oxidation states shown by transition elements.",
  isPYQ: true,
  year: 2024
},
{
  id: 105,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Chemical Bonding",
  topic: "VSEPR Theory",
  marks: 3,
  difficulty: "Medium",
  question: "Use VSEPR theory to predict the shape of NH3 and H2O.",
  isPYQ: true,
  year: 2022
},
{
  id: 106,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Redox Reactions",
  topic: "Oxidation and Reduction",
  marks: 2,
  difficulty: "Easy",
  question: "Define oxidation and reduction in terms of electron transfer.",
  isPYQ: false,
},
{
  id: 107,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Equilibrium",
  topic: "Acids and Bases",
  marks: 3,
  difficulty: "Medium",
  question: "Differentiate between Lewis and Bronsted-Lowry acids with examples.",
  isPYQ: true,
  year: 2024
},
{
  id: 108,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Thermodynamics",
  topic: "Enthalpy",
  marks: 4,
  difficulty: "Medium",
  question: "Explain different types of enthalpy changes with examples.",
  isPYQ: true,
  year: 2023
},
{
  id: 109,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Hydrocarbons",
  topic: "Isomerism",
  marks: 2,
  difficulty: "Easy",
  question: "Explain structural and geometrical isomerism in hydrocarbons.",
  isPYQ: true,
  year: 2021
},
{
  id: 110,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Haloalkanes",
  topic: "Reactions",
  marks: 3,
  difficulty: "Medium",
  question: "Write chemical reactions for haloalkanes with KOH (aq) and alcoholic KOH.",
  isPYQ: false,
},
{
  id: 111,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Alcohols and Phenols",
  topic: "Properties",
  marks: 3,
  difficulty: "Medium",
  question: "Differentiate between alcohols and phenols in terms of acidity and reactivity.",
  isPYQ: true,
  year: 2023
},
{
  id: 112,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Polymers",
  topic: "Natural vs Synthetic",
  marks: 2,
  difficulty: "Easy",
  question: "Give two examples each of natural and synthetic polymers.",
  isPYQ: true,
  year: 2024
},
{
  id: 113,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Environmental Chemistry",
  topic: "Ozone Layer",
  marks: 2,
  difficulty: "Easy",
  question: "What are the causes of ozone layer depletion? Mention its effects.",
  isPYQ: false,
},
{
  id: 114,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Biomolecules",
  topic: "Proteins",
  marks: 3,
  difficulty: "Medium",
  question: "Classify proteins based on structure. What are essential amino acids?",
  isPYQ: true,
  year: 2021
},
{
  id: 115,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "The s-Block Element",
  topic: "Reactivity",
  marks: 3,
  difficulty: "Medium",
  question: "Compare the reactivity of Group 1 and Group 2 elements with water.",
  isPYQ: false,
},
{
  id: 116,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "p-Block Elements",
  topic: "Group 13",
  marks: 4,
  difficulty: "Hard",
  question: "Discuss the trends in the physical and chemical properties of Group 13 elements.",
  isPYQ: true,
  year: 2023
},
{
  id: 117,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Electrochemistry",
  topic: "Electrolytic Cell",
  marks: 3,
  difficulty: "Medium",
  question: "Explain the working of an electrolytic cell with labelled diagram.",
  isPYQ: true,
  year: 2022
},
{
  id: 118,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Solid State",
  topic: "Packing Efficiency",
  marks: 3,
  difficulty: "Medium",
  question: "Calculate packing efficiency in FCC and BCC structures.",
  isPYQ: true,
  year: 2023
},
{
  id: 119,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Solutions",
  topic: "Colligative Properties",
  marks: 4,
  difficulty: "Hard",
  question: "Explain any two colligative properties with suitable formulae and units.",
  isPYQ: true,
  year: 2024
},
{
  id: 120,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Chemistry in Everyday Life",
  topic: "Drugs",
  marks: 2,
  difficulty: "Easy",
  question: "Define analgesics and antacids. Give one example of each.",
  isPYQ: false,
},
{
  id: 121,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Chemical Kinetics",
  topic: "Rate Constant",
  marks: 3,
  difficulty: "Medium",
  question: "Define rate constant. Write units and significance for first order reaction.",
  isPYQ: true,
  year: 2023
},
{
  id: 122,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "The d-Block Elements",
  topic: "Colour and Catalysis",
  marks: 3,
  difficulty: "Medium",
  question: "Explain why d-block elements show coloured compounds and act as catalysts.",
  isPYQ: true,
  year: 2022
},
{
  id: 123,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Atomic Structure",
  topic: "Quantum Numbers",
  marks: 2,
  difficulty: "Easy",
  question: "List the four quantum numbers and explain their significance.",
  isPYQ: true,
  year: 2023
},
{
  id: 124,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Classification of Elements",
  topic: "Modern Periodic Table",
  marks: 2,
  difficulty: "Easy",
  question: "State modern periodic law. Explain the classification of elements in modern periodic table.",
  isPYQ: true,
  year: 2022
},
{
  id: 125,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Solid State",
  topic: "Types of Solids",
  marks: 2,
  difficulty: "Easy",
  question: "Differentiate between crystalline and amorphous solids with examples.",
  isPYQ: false,
},
{
  id: 126,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Solutions",
  topic: "Concentration Terms",
  marks: 2,
  difficulty: "Easy",
  question: "Define molarity and mole fraction with their units.",
  isPYQ: false,
},
{
  id: 127,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Electrochemistry",
  topic: "Electrolytic Cell",
  marks: 3,
  difficulty: "Medium",
  question: "Differentiate between electrolytic and galvanic cells with diagrams.",
  isPYQ: true,
  year: 2023
},
{
  id: 128,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Chemical Kinetics",
  topic: "Rate of Reaction",
  marks: 2,
  difficulty: "Easy",
  question: "Define rate of reaction and rate constant.",
  isPYQ: false,
},
{
  id: 129,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Surface Chemistry",
  topic: "Catalysis",
  marks: 3,
  difficulty: "Medium",
  question: "What is a catalyst? Explain the types of catalysis with examples.",
  isPYQ: true,
  year: 2021
},
{
  id: 130,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "General Principles of Extraction",
  topic: "Metallurgy",
  marks: 3,
  difficulty: "Medium",
  question: "Explain the steps involved in the extraction of aluminium from bauxite.",
  isPYQ: true,
  year: 2022
},
{
  id: 131,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "The p-Block Elements",
  topic: "Group 16",
  marks: 2,
  difficulty: "Easy",
  question: "Why is O2 a gas and S8 a solid?",
  isPYQ: false,
},
{
  id: 132,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "The d-Block Elements",
  topic: "Transition Elements",
  marks: 3,
  difficulty: "Medium",
  question: "State three characteristics of d-block elements.",
  isPYQ: false,
},
{
  id: 133,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Coordination Compounds",
  topic: "Ligands",
  marks: 2,
  difficulty: "Easy",
  question: "What are ligands? Give two examples each of monodentate and bidentate ligands.",
  isPYQ: true,
  year: 2021
},
{
  id: 134,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Haloalkanes and Haloarenes",
  topic: "Properties",
  marks: 3,
  difficulty: "Medium",
  question: "Explain the boiling point trend of haloalkanes with respect to halogen atoms.",
  isPYQ: true,
  year: 2023
},
{
  id: 135,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Alcohols, Phenols and Ethers",
  topic: "Dehydration",
  marks: 3,
  difficulty: "Medium",
  question: "Write the mechanism of dehydration of alcohol to form alkene.",
  isPYQ: true,
  year: 2024
},
{
  id: 136,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Aldehydes and Ketones",
  topic: "Chemical Reactions",
  marks: 3,
  difficulty: "Medium",
  question: "Describe the nucleophilic addition reaction of aldehydes and ketones with HCN.",
  isPYQ: true,
  year: 2021
},
{
  id: 137,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Carboxylic Acids",
  topic: "Acidity",
  marks: 2,
  difficulty: "Easy",
  question: "Why are carboxylic acids more acidic than phenols?",
  isPYQ: false,
},
{
  id: 138,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Amines",
  topic: "Basicity",
  marks: 2,
  difficulty: "Easy",
  question: "Arrange primary, secondary, and tertiary amines in order of their basic strength in aqueous medium.",
  isPYQ: true,
  year: 2023
},
{
  id: 139,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Biomolecules",
  topic: "Proteins",
  marks: 3,
  difficulty: "Medium",
  question: "Define proteins. Distinguish between fibrous and globular proteins.",
  isPYQ: true,
  year: 2022
},
{
  id: 140,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Polymers",
  topic: "Types",
  marks: 2,
  difficulty: "Easy",
  question: "Define polymer. Give one example each of addition and condensation polymer.",
  isPYQ: false,
},
{
  id: 141,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Chemistry in Everyday Life",
  topic: "Antibiotics",
  marks: 2,
  difficulty: "Easy",
  question: "What are antibiotics? Give two examples.",
  isPYQ: false,
},
{
  id: 142,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "The Solid State",
  topic: "Packing Efficiency",
  marks: 3,
  difficulty: "Medium",
  question: "Define packing efficiency. What is its value for FCC?",
  isPYQ: true,
  year: 2023
},
{
  id: 143,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "The s-Block Elements",
  topic: "Properties of Alkali Metals",
  marks: 2,
  difficulty: "Easy",
  question: "Why are alkali metals stored in kerosene oil?",
  isPYQ: true,
  year: 2022
},
{
  id: 144,
  examLevel: "class12",
  subject: "Chemistry",
  chapter: "Environmental Chemistry",
  topic: "Water Pollution",
  marks: 2,
  difficulty: "Easy",
  question: "List two causes and effects of water pollution.",
  isPYQ: false,
},
// JEE CHEMISTRY QUESTION SET
{
    id: 145,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Atomic Structure",
    marks: 4,
    difficulty: "Easy",
    question: "The number of unpaired electrons in ground state of Cr (Z=24) is: (1) 4 (2) 5 (3) 6 (4) 1",
    isPYQ: true,
    year: 2024
  },
  {
    id: 146,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Chemical Bonding",
    marks: 4,
    difficulty: "Medium",
    question: "Which of the following has zero dipole moment? (1) NH₃ (2) H₂O (3) CO₂ (4) SO₂",
    isPYQ: true,
    year: 2023
  },
  {
    id: 147,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Thermodynamics",
    marks: 4,
    difficulty: "Medium",
    question: "For the reaction N₂(g) + 3H₂(g) → 2NH₃(g), ΔH is -92.4 kJ/mol. The reaction is: (1) Exothermic (2) Endothermic (3) Reversible (4) Irreversible",
    isPYQ: true,
    year: 2022
  },
  {
    id: 148,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Equilibrium",
    marks: 4,
    difficulty: "Medium",
    question: "If the concentration of H⁺ in a solution is 1 × 10⁻³ M, its pH is: (1) 3 (2) 4 (3) 5 (4) 2",
    isPYQ: true,
    year: 2021
  },
  {
    id: 149,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Electrochemistry",
    marks: 4,
    difficulty: "Hard",
    question: "The standard electrode potential of Zn²⁺/Zn and Cu²⁺/Cu are -0.76 V and +0.34 V respectively. The EMF of the cell Zn | Zn²⁺ || Cu²⁺ | Cu is: (1) 1.10 V (2) -1.10 V (3) 0.42 V (4) -0.42 V",
    isPYQ: true,
    year: 2024
  },
  {
    id: 150,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Chemical Kinetics",
    marks: 4,
    difficulty: "Medium",
    question: "For a first order reaction, the half-life period depends on: (1) Initial concentration (2) Temperature (3) Both (1) and (2) (4) Neither (1) nor (2)",
    isPYQ: true,
    year: 2023
  },
  {
    id: 151,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Surface Chemistry",
    marks: 4,
    difficulty: "Medium",
    question: "The cleansing action of soap is due to: (1) Emulsification (2) Adsorption (3) Coagulation (4) Dialysis",
    isPYQ: true,
    year: 2022
  },
  {
    id: 152,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Solid State",
    marks: 4,
    difficulty: "Medium",
    question: "The number of atoms per unit cell in a face-centered cubic (FCC) crystal is: (1) 2 (2) 4 (3) 6 (4) 8",
    isPYQ: true,
    year: 2021
  },
  {
    id: 153,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Solutions",
    marks: 4,
    difficulty: "Medium",
    question: "Which of the following is a colligative property? (1) Surface tension (2) Viscosity (3) Boiling point elevation (4) Density",
    isPYQ: true,
    year: 2023
  },
  {
    id: 154,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Redox Reactions",
    marks: 4,
    difficulty: "Easy",
    question: "The oxidation number of nitrogen in NO₂⁻ is: (1) +3 (2) +4 (3) +5 (4) +2",
    isPYQ: true,
    year: 2024
  },
  {
    id: 155,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Hydrogen",
    marks: 4,
    difficulty: "Easy",
    question: "Which of the following is the hardest form of ice? (1) Ice-I (2) Ice-II (3) Ice-VI (4) Ice-VII",
    isPYQ: true,
    year: 2022
  },
  {
    id: 156,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "s-Block Elements",
    marks: 4,
    difficulty: "Easy",
    question: "Which of the following alkali metals is the most electropositive? (1) Li (2) Na (3) K (4) Cs",
    isPYQ: true,
    year: 2023
  },
  {
    id: 157,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "p-Block Elements",
    marks: 4,
    difficulty: "Medium",
    question: "The oxidation state of sulphur in H₂SO₄ is: (1) +2 (2) +4 (3) +6 (4) +8",
    isPYQ: true,
    year: 2021
  },
  {
    id: 158,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "d- and f- Block Elements",
    marks: 4,
    difficulty: "Medium",
    question: "The colour of KMnO₄ is due to: (1) d-d transition (2) Charge transfer transition (3) Ligand to metal transition (4) Metal to ligand transition",
    isPYQ: true,
    year: 2024
  },
  {
    id: 159,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Coordination Compounds",
    marks: 4,
    difficulty: "Medium",
    question: "The IUPAC name of [Cr(NH₃)₄Cl₂]Cl is: (1) Tetrammine dichloro chromium(II) chloride (2) Tetrammine dichloro chromium(III) chloride (3) Tetraammine dichloridochromium(III) chloride (4) Tetraammine dichloro chromium(I) chloride",
    isPYQ: true,
    year: 2023
  },
  {
    id: 160,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Haloalkanes and Haloarenes",
    marks: 4,
    difficulty: "Easy",
    question: "Which compound will undergo SN1 reaction fastest? (1) CH₃Cl (2) (CH₃)₂CHCl (3) (CH₃)₃CCl (4) C₆H₅Cl",
    isPYQ: true,
    year: 2022
  },
  {
    id: 161,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Alcohols, Phenols and Ethers",
    marks: 4,
    difficulty: "Easy",
    question: "Which of the following gives iodoform test? (1) Methanol (2) Ethanol (3) Propanol (4) Benzyl alcohol",
    isPYQ: true,
    year: 2021
  },
  {
    id: 162,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Aldehydes, Ketones and Carboxylic Acids",
    marks: 4,
    difficulty: "Medium",
    question: "Which of the following will not give Tollens’ test? (1) Formaldehyde (2) Acetaldehyde (3) Acetone (4) Benzaldehyde",
    isPYQ: true,
    year: 2024
  },
  {
    id: 163,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Amines",
    marks: 4,
    difficulty: "Medium",
    question: "The reaction of primary amine with nitrous acid gives: (1) Amide (2) Alcohol (3) Nitro compound (4) Nitrile",
    isPYQ: true,
    year: 2023
  },
  {
    id: 164,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Biomolecules",
    marks: 4,
    difficulty: "Medium",
    question: "The sugar present in RNA is: (1) Ribose (2) Deoxyribose (3) Fructose (4) Glucose",
    isPYQ: true,
    year: 2021
  },
  {
    id: 165,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Polymers",
    marks: 4,
    difficulty: "Easy",
    question: "Which of the following is a condensation polymer? (1) Polyethylene (2) PVC (3) Nylon-6,6 (4) Polystyrene",
    isPYQ: true,
    year: 2022
  },
  {
    id: 166,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Environmental Chemistry",
    marks: 4,
    difficulty: "Easy",
    question: "Which gas is mainly responsible for greenhouse effect? (1) SO₂ (2) CO (3) CO₂ (4) NO₂",
    isPYQ: true,
    year: 2023
  },
  {
    id: 167,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Chemistry in Everyday Life",
    marks: 4,
    difficulty: "Easy",
    question: "Which of the following is an antiseptic? (1) Paracetamol (2) Aspirin (3) Dettol (4) Chloromycetin",
    isPYQ: true,
    year: 2021
  },
  {
    id: 168,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "General Organic Chemistry",
    marks: 4,
    difficulty: "Medium",
    question: "Which of the following is most acidic? (1) Phenol (2) Ethanol (3) Acetylene (4) Water",
    isPYQ: true,
    year: 2024
  },
  {
    id: 169,
    examLevel: "jee",
    chapter: "Chemistry",
    topic: "Isomerism",
    marks: 4,
    difficulty: "Medium",
    question: "Which of the following shows geometrical isomerism? (1) Propene (2) But-2-ene (3) 1-butene (4) Ethene",
    isPYQ: true,
    year: 2022
  },

// PHYSICS QUSTION SET FOR JEE
  {
    id: 170,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Motion in a Straight Line",
    marks: 4,
    difficulty: "Easy",
    question: "Two cars are travelling towards each other at speed of 20 m/s each. When the cars are 300 m apart, both the drivers apply brakes and the cars retard at the rate of 2 m/s^2. The distance between them when they come to rest is: (1) 200 m (2) 50 m (3) 100 m (4) 25 m",
    isPYQ: true,
    year: 2024
  },
  {
    id: 171,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Work, Energy and Power",
    marks: 4,
    difficulty: "Medium",
    question: "A block of mass 5 kg slides down a rough inclined plane making an angle of 30° with the horizontal. If the coefficient of friction is 0.2, the work done by friction in moving the block through 10 m is: (1) -50 J (2) -86.6 J (3) -100 J (4) -43.3 J",
    isPYQ: true,
    year: 2023
  },
  {
    id: 172,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Laws of Motion",
    marks: 4,
    difficulty: "Easy",
    question: "A 2 kg block is suspended by a string from the ceiling of an elevator which is accelerating upwards with 2 m/s². The tension in the string is: (1) 16 N (2) 20 N (3) 24 N (4) 28 N",
    isPYQ: true,
    year: 2022
  },
  {
    id: 173,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Rotational Motion",
    marks: 4,
    difficulty: "Hard",
    question: "A solid sphere rolls without slipping. If its linear speed is 5 m/s, its total kinetic energy is: (1) 50 J (2) 25 J (3) 37.5 J (4) 62.5 J",
    isPYQ: true,
    year: 2021
  },
  {
    id: 174,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Gravitation",
    marks: 4,
    difficulty: "Medium",
    question: "If the gravitational potential at the surface of a planet is -20 MJ/kg and at a height h above its surface it is -15 MJ/kg, the work done in lifting a 2 kg mass from the surface to height h is: (1) 5 MJ (2) 10 MJ (3) 20 MJ (4) 15 MJ",
    isPYQ: true,
    year: 2023
  },
  {
    id: 175,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Oscillations",
    marks: 4,
    difficulty: "Easy",
    question: "A particle performs SHM with amplitude 4 cm. Its maximum speed is 16 cm/s. The period of oscillation is: (1) π s (2) π/2 s (3) 2π s (4) 1 s",
    isPYQ: true,
    year: 2024
  },
  {
    id: 176,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Waves",
    marks: 4,
    difficulty: "Medium",
    question: "Two sound waves of frequencies 256 Hz and 260 Hz produce 5 beats in 1 second. The speed of sound is 340 m/s. The wavelength of the wave with 256 Hz is: (1) 1.33 m (2) 1.25 m (3) 1.50 m (4) 1.00 m",
    isPYQ: true,
    year: 2022
  },
  {
    id: 177,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Heat and Thermodynamics",
    marks: 4,
    difficulty: "Medium",
    question: "A Carnot engine operates between 500 K and 300 K. If it absorbs 600 J heat from the source, the work done by the engine is: (1) 200 J (2) 240 J (3) 360 J (4) 300 J",
    isPYQ: true,
    year: 2021
  },
  {
    id: 178,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Electrostatics",
    marks: 4,
    difficulty: "Hard",
    question: "Two point charges +3 µC and -3 µC are placed 0.2 m apart in air. The electric potential at a point midway between them is: (1) Zero (2) 270 kV (3) -270 kV (4) 0.54 MV",
    isPYQ: true,
    year: 2024
  },
  {
    id: 179,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Current Electricity",
    marks: 4,
    difficulty: "Easy",
    question: "The resistance of a wire is 10 ohms at 20°C and 12 ohms at 100°C. The temperature coefficient of resistance is: (1) 0.00125/°C (2) 0.0025/°C (3) 0.003/°C (4) 0.004/°C",
    isPYQ: true,
    year: 2023
  },
  {
    id: 180,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Magnetism",
    marks: 4,
    difficulty: "Medium",
    question: "A circular coil of radius 0.1 m has 100 turns and carries a current of 1 A. The magnetic field at its centre is: (1) 6.28 × 10⁻⁴ T (2) 1.26 × 10⁻⁴ T (3) 2.0 × 10⁻⁴ T (4) 3.14 × 10⁻⁴ T",
    isPYQ: true,
    year: 2024
  },
  {
    id: 181,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Electromagnetic Induction",
    marks: 4,
    difficulty: "Hard",
    question: "A coil of inductance 2 H and resistance 10 Ω is connected to a 10 V battery. The energy stored in the magnetic field at steady state is: (1) 1 J (2) 0 J (3) 2 J (4) 5 J",
    isPYQ: true,
    year: 2022
  },
  {
    id: 182,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Alternating Current",
    marks: 4,
    difficulty: "Medium",
    question: "An AC voltage V = 200 sin(100πt) is applied to a resistor of 50 Ω. The RMS current is: (1) 2 A (2) 2.83 A (3) 4 A (4) 5 A",
    isPYQ: true,
    year: 2021
  },
  {
    id: 183,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Electromagnetic Waves",
    marks: 4,
    difficulty: "Easy",
    question: "Which of the following electromagnetic waves has the highest frequency? (1) Microwaves (2) X-rays (3) Infrared (4) Radio waves",
    isPYQ: true,
    year: 2023
  },
  {
    id: 184,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Ray Optics",
    marks: 4,
    difficulty: "Medium",
    question: "A concave mirror produces an image twice the size of the object. If the object is placed 15 cm from the mirror, its focal length is: (1) 5 cm (2) 10 cm (3) 15 cm (4) 30 cm",
    isPYQ: true,
    year: 2024
  },
  {
    id: 185,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Wave Optics",
    marks: 4,
    difficulty: "Medium",
    question: "In Young's double slit experiment, the separation between the slits is 0.5 mm and the screen is 1 m away. If the wavelength of light used is 600 nm, the fringe width is: (1) 0.6 mm (2) 1.2 mm (3) 0.12 mm (4) 1.0 mm",
    isPYQ: true,
    year: 2022
  },
  {
    id: 186,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Modern Physics",
    marks: 4,
    difficulty: "Medium",
    question: "The de Broglie wavelength of an electron accelerated through a potential difference of 100 V is approximately: (1) 1.23 nm (2) 0.123 nm (3) 3.7 nm (4) 0.037 nm",
    isPYQ: true,
    year: 2021
  },
  {
    id: 187,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Dual Nature of Matter",
    marks: 4,
    difficulty: "Hard",
    question: "In photoelectric effect, the stopping potential for a certain metal is 2 V when light of wavelength 400 nm is used. The work function of the metal is: (1) 2.1 eV (2) 3.1 eV (3) 1.1 eV (4) 4.1 eV",
    isPYQ: true,
    year: 2023
  },
  {
    id: 188,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Atoms",
    marks: 4,
    difficulty: "Medium",
    question: "The radius of the first Bohr orbit in hydrogen atom is 0.53 Å. The radius of the third orbit is: (1) 1.59 Å (2) 4.77 Å (3) 0.18 Å (4) 2.12 Å",
    isPYQ: true,
    year: 2022
  },
  {
    id: 189,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Nuclei",
    marks: 4,
    difficulty: "Medium",
    question: "The half-life of a radioactive element is 10 days. The time taken for its activity to reduce to one-eighth of its original value is: (1) 10 days (2) 20 days (3) 30 days (4) 40 days",
    isPYQ: true,
    year: 2024
  },
  {
    id: 190,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Semiconductors",
    marks: 4,
    difficulty: "Easy",
    question: "In an n-type semiconductor, the majority carriers are: (1) Holes (2) Electrons (3) Protons (4) Neutrons",
    isPYQ: true,
    year: 2023
  },
  {
    id: 191,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Communication Systems",
    marks: 4,
    difficulty: "Easy",
    question: "Which of the following is used for communication through optical fibres? (1) Microwaves (2) X-rays (3) Infrared waves (4) Ultraviolet rays",
    isPYQ: true,
    year: 2021
  },
  {
    id: 192,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Units and Dimensions",
    marks: 4,
    difficulty: "Easy",
    question: "The dimensional formula of Planck's constant is: (1) ML²T⁻¹ (2) ML²T⁻² (3) MLT⁻¹ (4) ML⁻¹T⁻¹",
    isPYQ: true,
    year: 2022
  },
  {
    id: 193,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Error and Instrumentation",
    marks: 4,
    difficulty: "Easy",
    question: "If the percentage error in measuring radius is 2%, the percentage error in calculating the volume of the sphere is: (1) 2% (2) 4% (3) 6% (4) 8%",
    isPYQ: true,
    year: 2024
  },
  {
    id: 194,
    examLevel: "jee",
    chapter: "Physics",
    topic: "Experimental Physics",
    marks: 4,
    difficulty: "Easy",
    question: "A student uses a meter scale to measure the length of a rod and finds it to be 50.0 cm. If the least count of the scale is 1 mm, the percentage error in measurement is: (1) 0.1% (2) 0.2% (3) 0.5% (4) 1%",
    isPYQ: true,
    year: 2023
  }
];
